function [bndrs, dmode_l_im, num_objects, temp, t_centr, mean_inten_all, mean_inten, min_inten, max_inten, ...
    Iout_ncirc, Iout_circ, labeled_im, labeled_im_circ, obj_del, distances, labeled_im_nucleus, labeled_im_cytoplasm] = ...
        talCountParams(data0, B3, Iout, binaryImage2, param_flag, circ_param, obj_area_thresh_circ_itsty, ...
    itsty_lvl, obj_area_thresh_itsty, obj_area_thresh, add_map, manualcorr_flag)

[bndrs, labeled_image, dmode_l_im, num_objects, temp, ...
    mean_inten_all, mean_inten, min_inten, max_inten] = countparamsext(data0, Iout, param_flag);

[Iout_ncirc, Iout_circ, labeled_im, labeled_im_circ, bndrs, temp, obj_del, num_objects, mean_inten, ...
    max_inten, min_inten, mean_inten_all, t_centr, varargout] = ...
        talclassify(labeled_image, B3, Iout, num_objects, temp, data0, mean_inten, max_inten, ...
        min_inten, mean_inten_all, circ_param, obj_area_thresh_circ_itsty, itsty_lvl, bndrs, ...
        obj_area_thresh_itsty, obj_area_thresh, add_map, manualcorr_flag);

% Gradient traktowany jest jako stosunek różnicy intensywności pomiędzy
% centroidem intensywności obiektu a jego brzegiem w miejscu najkrótszej
[distances, temp] = talRatioGoI(num_objects, bndrs, temp, data0); %wyznaczanie ratio i gradientu

% Estimation of label map depending on the location of objects
[labeled_im_nucleus, labeled_im_cytoplasm, temp] = talFindAboveNucleus(labeled_im, ...
    num_objects, binaryImage2, temp);
    
figure(102);
imshow(Iout_ncirc); title('Binary map after object selection');

end